### PR TITLE
Bootstrapify++

### PR DESCRIPTION
**Pull request by gzhihongwei**
Improves upon initially merged `bootstrapify` branch code by changing cursor mode for images to `pointer` (image) and simplifying verification template

Readdresses #13

### CODE REVIEW

**Review by tiyekm — APPROVED** [review]
Looks good, cursor is now pointer.

**Review by tiyekm — APPROVED** [review]

**Review by tiyekm — APPROVED** [review]
approved review

**Review by tiyeAKM — APPROVED** [review]
Styling is simplified but we can easily change any aesthetic factors later if we want. Like the rounded images, 200 px image width should be good for most browser viewports. Column resizing adjusts images nicely without css media queries. May need to change footer styling in future, but that relates to the app's styling as well.

**Review by tiyeAKM — APPROVED** [review]
Looks good, cursor is now pointer.

**Pull request merged**
