### PR TITLE
Prevents back button from going to previous response

### PR DESCRIPTION
**Pull request by gzhihongwei**
Adds a small script to prevent going back to previous response in the main body of the identification or verification tasks.

### CODE REVIEW

**Comment by ryansdowning** [comment]
This fix definitely helped, but there's still a couple other issues (which, considering my limited front-end knowledge, I'm not sure we can do anything about). I can still go back from `127.0.0.1:5000/<identification/verification>/1` to `127.0.0.1:5000/<identification/verification>`, this currently regenerates the images for question 1, which I would deem "cheating". You can also "cheat" by just typing in the url `127.0.0.1:5000/<identification/verification>/<1-50>`.

**Comment by gzhihongwei** [comment]
@ryansdowning I tried to address this for 4-5 hours today, but sessions are super finnicky and are not really worth the trouble to prevent this imo. It's a very big pain to identify which state to be in and render, so I think it would be easier to just tell the user not to use the address bar or something.

**Comment by ryansdowning** [comment]
@gzhihongwei Thanks for looking into it, I figured it would be pretty tricky (I probably would've given up long before you haha). I doubt it will be a common issue, if at all. Probably best to just not mention the address bar as to not give them any ideas. I might even be able to circumvent this on the database end by seeing if the user already answered a given question, and ignoring any duplicate responses. Unrelated to this PR, but could we attach a unique `user_id` to each session and have that return as part of all forms (question answers, self-identification, etc.).

**Review by ryansdowning — APPROVED** [review]
LGTM

**Pull request merged**
